export const API_BASE_URL = "http://localhost:8050/app";

export const COUNTRIES = [
  { isoCode: "AF", phoneCode: 93, name: "Afghanistan" },
  { isoCode: "AX", phoneCode: 358, name: "Aland Islands" },
  { isoCode: "AL", phoneCode: 355, name: "Albania" },
  { isoCode: "DZ", phoneCode: 213, name: "Algeria" },
  { isoCode: "AS", phoneCode: 1684, name: "American Samoa" },
  { isoCode: "AD", phoneCode: 376, name: "Andorra" },
  { isoCode: "AO", phoneCode: 244, name: "Angola" },
  { isoCode: "AI", phoneCode: 1264, name: "Anguilla" },
  { isoCode: "AQ", phoneCode: 0, name: "Antarctica" },
  { isoCode: "AG", phoneCode: 1268, name: "Antigua and Barbuda" },
  { isoCode: "AR", phoneCode: 54, name: "Argentina" },
  { isoCode: "AM", phoneCode: 374, name: "Armenia" },
  { isoCode: "AW", phoneCode: 297, name: "Aruba" },
  { isoCode: "AU", phoneCode: 61, name: "Australia" },
  { isoCode: "AT", phoneCode: 43, name: "Austria" },
  { isoCode: "AZ", phoneCode: 994, name: "Azerbaijan" },
  { isoCode: "BS", phoneCode: 1242, name: "Bahamas" },
  { isoCode: "BH", phoneCode: 973, name: "Bahrain" },
  { isoCode: "BD", phoneCode: 880, name: "Bangladesh" },
  { isoCode: "BB", phoneCode: 1246, name: "Barbados" },
  { isoCode: "BY", phoneCode: 375, name: "Belarus" },
  { isoCode: "BE", phoneCode: 32, name: "Belgium" },
  { isoCode: "BZ", phoneCode: 501, name: "Belize" },
  { isoCode: "BJ", phoneCode: 229, name: "Benin" },
  { isoCode: "BM", phoneCode: 1441, name: "Bermuda" },
  { isoCode: "BT", phoneCode: 975, name: "Bhutan" },
  { isoCode: "BO", phoneCode: 591, name: "Bolivia" },
  { isoCode: "BQ", phoneCode: 599, name: "Bonaire, Sint Eustatius and Saba" },
  { isoCode: "BA", phoneCode: 387, name: "Bosnia and Herzegovina" },
  { isoCode: "BW", phoneCode: 267, name: "Botswana" },
  { isoCode: "BV", phoneCode: 0, name: "Bouvet Island" },
  { isoCode: "BR", phoneCode: 55, name: "Brazil" },
  { isoCode: "IO", phoneCode: 246, name: "British Indian Ocean Territory" },
  { isoCode: "BN", phoneCode: 673, name: "Brunei Darussalam" },
  { isoCode: "BG", phoneCode: 359, name: "Bulgaria" },
  { isoCode: "BF", phoneCode: 226, name: "Burkina Faso" },
  { isoCode: "BI", phoneCode: 257, name: "Burundi" },
  { isoCode: "KH", phoneCode: 855, name: "Cambodia" },
  { isoCode: "CM", phoneCode: 237, name: "Cameroon" },
  { isoCode: "CA", phoneCode: 1, name: "Canada" },
  { isoCode: "CV", phoneCode: 238, name: "Cape Verde" },
  { isoCode: "KY", phoneCode: 1345, name: "Cayman Islands" },
  { isoCode: "CF", phoneCode: 236, name: "Central African Republic" },
  { isoCode: "TD", phoneCode: 235, name: "Chad" },
  { isoCode: "CL", phoneCode: 56, name: "Chile" },
  { isoCode: "CN", phoneCode: 86, name: "China" },
  { isoCode: "CX", phoneCode: 61, name: "Christmas Island" },
  { isoCode: "CC", phoneCode: 672, name: "Cocos (Keeling) Islands" },
  { isoCode: "CO", phoneCode: 57, name: "Colombia" },
  { isoCode: "KM", phoneCode: 269, name: "Comoros" },
  { isoCode: "CG", phoneCode: 242, name: "Congo" },
  {
    isoCode: "CD",
    phoneCode: 242,
    name: "Congo, the Democratic Republic of the",
  },
  { isoCode: "CK", phoneCode: 682, name: "Cook Islands" },
  { isoCode: "CR", phoneCode: 506, name: "Costa Rica" },
  { isoCode: "CI", phoneCode: 225, name: "Cote D'Ivoire" },
  { isoCode: "HR", phoneCode: 385, name: "Croatia" },
  { isoCode: "CU", phoneCode: 53, name: "Cuba" },
  { isoCode: "CW", phoneCode: 599, name: "Curacao" },
  { isoCode: "CY", phoneCode: 357, name: "Cyprus" },
  { isoCode: "CZ", phoneCode: 420, name: "Czech Republic" },
  { isoCode: "DK", phoneCode: 45, name: "Denmark" },
  { isoCode: "DJ", phoneCode: 253, name: "Djibouti" },
  { isoCode: "DM", phoneCode: 1767, name: "Dominica" },
  { isoCode: "DO", phoneCode: 1, name: "Dominican Republic" },
  { isoCode: "EC", phoneCode: 593, name: "Ecuador" },
  { isoCode: "EG", phoneCode: 20, name: "Egypt" },
  { isoCode: "SV", phoneCode: 503, name: "El Salvador" },
  { isoCode: "GQ", phoneCode: 240, name: "Equatorial Guinea" },
  { isoCode: "ER", phoneCode: 291, name: "Eritrea" },
  { isoCode: "EE", phoneCode: 372, name: "Estonia" },
  { isoCode: "ET", phoneCode: 251, name: "Ethiopia" },
  { isoCode: "FK", phoneCode: 500, name: "Falkland Islands (Malvinas)" },
  { isoCode: "FO", phoneCode: 298, name: "Faroe Islands" },
  { isoCode: "FJ", phoneCode: 679, name: "Fiji" },
  { isoCode: "FI", phoneCode: 358, name: "Finland" },
  { isoCode: "FR", phoneCode: 33, name: "France" },
  { isoCode: "GF", phoneCode: 594, name: "French Guiana" },
  { isoCode: "PF", phoneCode: 689, name: "French Polynesia" },
  { isoCode: "TF", phoneCode: 0, name: "French Southern Territories" },
  { isoCode: "GA", phoneCode: 241, name: "Gabon" },
  { isoCode: "GM", phoneCode: 220, name: "Gambia" },
  { isoCode: "GE", phoneCode: 995, name: "Georgia" },
  { isoCode: "DE", phoneCode: 49, name: "Germany" },
  { isoCode: "GH", phoneCode: 233, name: "Ghana" },
  { isoCode: "GI", phoneCode: 350, name: "Gibraltar" },
  { isoCode: "GR", phoneCode: 30, name: "Greece" },
  { isoCode: "GL", phoneCode: 299, name: "Greenland" },
  { isoCode: "GD", phoneCode: 1473, name: "Grenada" },
  { isoCode: "GP", phoneCode: 590, name: "Guadeloupe" },
  { isoCode: "GU", phoneCode: 1671, name: "Guam" },
  { isoCode: "GT", phoneCode: 502, name: "Guatemala" },
  { isoCode: "GG", phoneCode: 44, name: "Guernsey" },
  { isoCode: "GN", phoneCode: 224, name: "Guinea" },
  { isoCode: "GW", phoneCode: 245, name: "Guinea-Bissau" },
  { isoCode: "GY", phoneCode: 592, name: "Guyana" },
  { isoCode: "HT", phoneCode: 509, name: "Haiti" },
  { isoCode: "HM", phoneCode: 0, name: "Heard Island and Mcdonald Islands" },
  { isoCode: "VA", phoneCode: 39, name: "Holy See (Vatican City State)" },
  { isoCode: "HN", phoneCode: 504, name: "Honduras" },
  { isoCode: "HK", phoneCode: 852, name: "Hong Kong" },
  { isoCode: "HU", phoneCode: 36, name: "Hungary" },
  { isoCode: "IS", phoneCode: 354, name: "Iceland" },
  { isoCode: "IN", phoneCode: 91, name: "India" },
  { isoCode: "ID", phoneCode: 62, name: "Indonesia" },
  { isoCode: "IR", phoneCode: 98, name: "Iran, Islamic Republic of" },
  { isoCode: "IQ", phoneCode: 964, name: "Iraq" },
  { isoCode: "IE", phoneCode: 353, name: "Ireland" },
  { isoCode: "IM", phoneCode: 44, name: "Isle of Man" },
  { isoCode: "IL", phoneCode: 972, name: "Israel" },
  { isoCode: "IT", phoneCode: 39, name: "Italy" },
  { isoCode: "JM", phoneCode: 1876, name: "Jamaica" },
  { isoCode: "JP", phoneCode: 81, name: "Japan" },
  { isoCode: "JE", phoneCode: 44, name: "Jersey" },
  { isoCode: "JO", phoneCode: 962, name: "Jordan" },
  { isoCode: "KZ", phoneCode: 7, name: "Kazakhstan" },
  { isoCode: "KE", phoneCode: 254, name: "Kenya" },
  { isoCode: "KI", phoneCode: 686, name: "Kiribati" },
  {
    isoCode: "KP",
    phoneCode: 850,
    name: "Korea, Democratic People's Republic of",
  },
  { isoCode: "KR", phoneCode: 82, name: "Korea, Republic of" },
  { isoCode: "XK", phoneCode: 383, name: "Kosovo" },
  { isoCode: "KW", phoneCode: 965, name: "Kuwait" },
  { isoCode: "KG", phoneCode: 996, name: "Kyrgyzstan" },
  { isoCode: "LA", phoneCode: 856, name: "Lao People's Democratic Republic" },
  { isoCode: "LV", phoneCode: 371, name: "Latvia" },
  { isoCode: "LB", phoneCode: 961, name: "Lebanon" },
  { isoCode: "LS", phoneCode: 266, name: "Lesotho" },
  { isoCode: "LR", phoneCode: 231, name: "Liberia" },
  { isoCode: "LY", phoneCode: 218, name: "Libyan Arab Jamahiriya" },
  { isoCode: "LI", phoneCode: 423, name: "Liechtenstein" },
  { isoCode: "LT", phoneCode: 370, name: "Lithuania" },
  { isoCode: "LU", phoneCode: 352, name: "Luxembourg" },
  { isoCode: "MO", phoneCode: 853, name: "Macao" },
  { isoCode: "MG", phoneCode: 261, name: "Madagascar" },
  { isoCode: "MW", phoneCode: 265, name: "Malawi" },
  { isoCode: "MY", phoneCode: 60, name: "Malaysia" },
  { isoCode: "MV", phoneCode: 960, name: "Maldives" },
  { isoCode: "ML", phoneCode: 223, name: "Mali" },
  { isoCode: "MT", phoneCode: 356, name: "Malta" },
  { isoCode: "MH", phoneCode: 692, name: "Marshall Islands" },
  { isoCode: "MQ", phoneCode: 596, name: "Martinique" },
  { isoCode: "MR", phoneCode: 222, name: "Mauritania" },
  { isoCode: "MU", phoneCode: 230, name: "Mauritius" },
  { isoCode: "YT", phoneCode: 269, name: "Mayotte" },
  { isoCode: "MX", phoneCode: 52, name: "Mexico" },
  { isoCode: "FM", phoneCode: 691, name: "Micronesia, Federated States of" },
  { isoCode: "MD", phoneCode: 373, name: "Moldova, Republic of" },
  { isoCode: "MC", phoneCode: 377, name: "Monaco" },
  { isoCode: "MN", phoneCode: 976, name: "Mongolia" },
  { isoCode: "ME", phoneCode: 382, name: "Montenegro" },
  { isoCode: "MS", phoneCode: 1664, name: "Montserrat" },
  { isoCode: "MA", phoneCode: 212, name: "Morocco" },
  { isoCode: "MZ", phoneCode: 258, name: "Mozambique" },
  { isoCode: "MM", phoneCode: 95, name: "Myanmar" },
  { isoCode: "NA", phoneCode: 264, name: "Namibia" },
  { isoCode: "NR", phoneCode: 674, name: "Nauru" },
  { isoCode: "NP", phoneCode: 977, name: "Nepal" },
  { isoCode: "NL", phoneCode: 31, name: "Netherlands" },
  { isoCode: "AN", phoneCode: 599, name: "Netherlands Antilles" },
  { isoCode: "NC", phoneCode: 687, name: "New Caledonia" },
  { isoCode: "NZ", phoneCode: 64, name: "New Zealand" },
  { isoCode: "NI", phoneCode: 505, name: "Nicaragua" },
  { isoCode: "NE", phoneCode: 227, name: "Niger" },
  { isoCode: "NG", phoneCode: 234, name: "Nigeria" },
  { isoCode: "NU", phoneCode: 683, name: "Niue" },
  { isoCode: "NF", phoneCode: 672, name: "Norfolk Island" },
  { isoCode: "MP", phoneCode: 1670, name: "Northern Mariana Islands" },
  { isoCode: "MK", phoneCode: 389, name: "North Macedonia" },
  { isoCode: "NO", phoneCode: 47, name: "Norway" },
  { isoCode: "OM", phoneCode: 968, name: "Oman" },
  { isoCode: "PK", phoneCode: 92, name: "Pakistan" },
  { isoCode: "PW", phoneCode: 680, name: "Palau" },
  { isoCode: "PS", phoneCode: 970, name: "Palestinian Territory, Occupied" },
  { isoCode: "PA", phoneCode: 507, name: "Panama" },
  { isoCode: "PG", phoneCode: 675, name: "Papua New Guinea" },
  { isoCode: "PY", phoneCode: 595, name: "Paraguay" },
  { isoCode: "PE", phoneCode: 51, name: "Peru" },
  { isoCode: "PH", phoneCode: 63, name: "Philippines" },
  { isoCode: "PN", phoneCode: 0, name: "Pitcairn" },
  { isoCode: "PL", phoneCode: 48, name: "Poland" },
  { isoCode: "PT", phoneCode: 351, name: "Portugal" },
  { isoCode: "PR", phoneCode: 1787, name: "Puerto Rico" },
  { isoCode: "QA", phoneCode: 974, name: "Qatar" },
  { isoCode: "RE", phoneCode: 262, name: "Reunion" },
  { isoCode: "RO", phoneCode: 40, name: "Romania" },
  { isoCode: "RU", phoneCode: 7, name: "Russian Federation" },
  { isoCode: "RW", phoneCode: 250, name: "Rwanda" },
  { isoCode: "BL", phoneCode: 590, name: "Saint Barthelemy" },
  { isoCode: "SH", phoneCode: 290, name: "Saint Helena" },
  { isoCode: "KN", phoneCode: 1869, name: "Saint Kitts and Nevis" },
  { isoCode: "LC", phoneCode: 1758, name: "Saint Lucia" },
  { isoCode: "MF", phoneCode: 590, name: "Saint Martin" },
  { isoCode: "PM", phoneCode: 508, name: "Saint Pierre and Miquelon" },
  {
    isoCode: "VC",
    phoneCode: 1784,
    name: "Saint Vincent and the Grenadines",
  },
  { isoCode: "WS", phoneCode: 684, name: "Samoa" },
  { isoCode: "SM", phoneCode: 378, name: "San Marino" },
  { isoCode: "ST", phoneCode: 239, name: "Sao Tome and Principe" },
  { isoCode: "SA", phoneCode: 966, name: "Saudi Arabia" },
  { isoCode: "SN", phoneCode: 221, name: "Senegal" },
  { isoCode: "RS", phoneCode: 381, name: "Serbia" },
  { isoCode: "SC", phoneCode: 248, name: "Seychelles" },
  { isoCode: "SL", phoneCode: 232, name: "Sierra Leone" },
  { isoCode: "SG", phoneCode: 65, name: "Singapore" },
  { isoCode: "SX", phoneCode: 1, name: "Sint Maarten" },
  { isoCode: "SK", phoneCode: 421, name: "Slovakia" },
  { isoCode: "SI", phoneCode: 386, name: "Slovenia" },
  { isoCode: "SB", phoneCode: 677, name: "Solomon Islands" },
  { isoCode: "SO", phoneCode: 252, name: "Somalia" },
  { isoCode: "ZA", phoneCode: 27, name: "South Africa" },
  {
    isoCode: "GS",
    phoneCode: 0,
    name: "South Georgia and the South Sandwich Islands",
  },
  { isoCode: "SS", phoneCode: 211, name: "South Sudan" },
  { isoCode: "ES", phoneCode: 34, name: "Spain" },
  { isoCode: "LK", phoneCode: 94, name: "Sri Lanka" },
  { isoCode: "SD", phoneCode: 249, name: "Sudan" },
  { isoCode: "SR", phoneCode: 597, name: "Suriname" },
  { isoCode: "SJ", phoneCode: 47, name: "Svalbard and Jan Mayen" },
  { isoCode: "SZ", phoneCode: 268, name: "Swaziland" },
  { isoCode: "SE", phoneCode: 46, name: "Sweden" },
  { isoCode: "CH", phoneCode: 41, name: "Switzerland" },
  { isoCode: "SY", phoneCode: 963, name: "Syrian Arab Republic" },
  { isoCode: "TW", phoneCode: 886, name: "Taiwan, Province of China" },
  { isoCode: "TJ", phoneCode: 992, name: "Tajikistan" },
  { isoCode: "TZ", phoneCode: 255, name: "Tanzania, United Republic of" },
  { isoCode: "TH", phoneCode: 66, name: "Thailand" },
  { isoCode: "TL", phoneCode: 670, name: "Timor-Leste" },
  { isoCode: "TG", phoneCode: 228, name: "Togo" },
  { isoCode: "TK", phoneCode: 690, name: "Tokelau" },
  { isoCode: "TO", phoneCode: 676, name: "Tonga" },
  { isoCode: "TT", phoneCode: 1868, name: "Trinidad and Tobago" },
  { isoCode: "TN", phoneCode: 216, name: "Tunisia" },
  { isoCode: "TR", phoneCode: 90, name: "Turkey" },
  { isoCode: "TM", phoneCode: 993, name: "Turkmenistan" },
  { isoCode: "TC", phoneCode: 1649, name: "Turks and Caicos Islands" },
  { isoCode: "TV", phoneCode: 688, name: "Tuvalu" },
  { isoCode: "UG", phoneCode: 256, name: "Uganda" },
  { isoCode: "UA", phoneCode: 380, name: "Ukraine" },
  { isoCode: "AE", phoneCode: 971, name: "United Arab Emirates" },
  { isoCode: "GB", phoneCode: 44, name: "United Kingdom" },
  { isoCode: "US", phoneCode: 1, name: "United States" },
  {
    isoCode: "UM",
    phoneCode: 1,
    name: "United States Minor Outlying Islands",
  },
  { isoCode: "UY", phoneCode: 598, name: "Uruguay" },
  { isoCode: "UZ", phoneCode: 998, name: "Uzbekistan" },
  { isoCode: "VU", phoneCode: 678, name: "Vanuatu" },
  { isoCode: "VE", phoneCode: 58, name: "Venezuela" },
  { isoCode: "VN", phoneCode: 84, name: "Viet Nam" },
  { isoCode: "VG", phoneCode: 1284, name: "Virgin Islands, British" },
  { isoCode: "VI", phoneCode: 1340, name: "Virgin Islands, U.s." },
  { isoCode: "WF", phoneCode: 681, name: "Wallis and Futuna" },
  { isoCode: "EH", phoneCode: 212, name: "Western Sahara" },
  { isoCode: "YE", phoneCode: 967, name: "Yemen" },
  { isoCode: "ZM", phoneCode: 260, name: "Zambia" },
  { isoCode: "ZW", phoneCode: 263, name: "Zimbabwe" },
];
